spring.application.name=auth-service
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/auth_db
spring.datasource.username=root
spring.datasource.password=Hruthvik@2025sql

spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

